version: '3'
services:
  php:
    build: .
    ports:
        - 9000:9000
    volumes:
        - ./www:/var/www
        - logvolume01:/var/log
    depends_on:
        - mysql
  mysql:
    image: mysql
    restart: always
    env_file:
        - ".env"
    environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
        - 3306:3306
    volumes:
        - ./data/db/mysql:/var/lib/mysql
  myadmin:
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      ports:
          - 8080:80
      environment:
          - PMA_ARBITRARY=1
          - PMA_HOST=${MYSQL_HOST}
      restart: always
      depends_on:
          - mysql
  nginx:
    image: nginx
    volumes:
        - ./nginx/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        - ./www:/var/www
    environment:
        - NGINX_HOST=${NGINX_HOST}
    ports:
        - 80:80
        - 443:443
    restart: always
    depends_on:
        - php
volumes:
  logvolume01: {}