version: "3"
services:
  web:
    image: social-network-backend
    volumes:
      - ./public:/app/public
    depends_on:
      - redis
      - mongo
    env_file:
        - ".env"
    networks:
      - webnet
  nginx:
    image: nginx
    volumes:
      - ./config.template:/etc/nginx/conf.d/config.template
      - ./public:/public
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
    depends_on:
      - web
    command: /bin/bash -c "cat < /etc/nginx/conf.d/config.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
#    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/config.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    networks:
      - webnet
  mongo:
    image: mongo:latest
    volumes:
      - ./data/mongo/data:/data
    ports:
      - "27017:27017"
    networks:
      - webnet
  redis:
    image: redis
    networks:
      - webnet
networks:
  webnet:
